
add_newline = true

format = """
[┏┫ $time ┣ $hostname@$username \\[$directory\\]](bold red)
[┃ ](bold red) $all\
[┗](bold red)$character"""

[character]
success_symbol = "[❯](bold red)"

[hostname]
ssh_only = false
format = "[$ssh_symbol$hostname]($style)"

[username]
show_always = true
format = "[$user]($style)"

[directory]
format = "[$path]($style)[$read_only]($read_only_style)"

[time]
disabled = false
format = '[$time]($style)'

[git_branch]
format = " [$symbol$branch(:$remote_branch)]($style) "
[git_status]
disabled = true

[rust]
disabled = true

[battery]
disabled = true

